Update

diff --git a/.github/workflows/test-workflow.yml b/.github/workflows/test-workflow.yml
--- a/.github/workflows/test-workflow.yml
+++ b/.github/workflows/test-workflow.yml
@@ -1,21 +1,29 @@
-name: Test Workflow
+name: Test
 
 on:
   workflow_dispatch:
 
 jobs:
-  send-messages:
+  build-and-test:
     runs-on: ubuntu-latest
-
     steps:
-      - name: Force Fail
-        run: exit 1  # Intentional failure for test
+    - uses: actions/checkout@v2
 
-  redrive:
-    runs-on: ubuntu-latest
-    needs: send-messages
-    if: needs.send-messages.result == 'failure'
+    # Mock to test workflow
+    - name: Test app
+      id: test-app # will be referenced later
+      run: |
+        echo "Testing app (randomly fails)"
+        if [[ $(($RANDOM % 2)) == 0 ]]; then exit 0; else exit 1; fi
 
-    steps:
-      - name: Notify
-        run: echo "Redrive triggered because send-messages failed"
+    # runs always
+    - name: test-clean
+      if: always()
+      run: echo "Cleanup after tests"
+
+    # runs if previous jobs failed and test-app was not successful (failure/cancelled)
+    - name: action-slack
+      if: failure() && steps.test-app.outcome != 'success'
+      run: |
+        echo "Run action-slack"
+        echo "Result of test-app was '${{ steps.test-app.outcome }}'"
